"""empty message

Revision ID: 16fe323926b3
Revises: 
Create Date: 2025-01-10 21:13:44.437683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fe323926b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=120), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('modes', sa.String(length=50), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('system_requirements', sa.Text(), nullable=False),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('media', sa.String(length=250), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('players', sa.Integer(), nullable=False),
    sa.Column('related_games', sa.String(length=250), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=180), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('game')
    # ### end Alembic commands ###
