"""empty message

Revision ID: 763ff6b2080e
Revises: 
Create Date: 2025-01-12 01:18:22.978191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763ff6b2080e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('modes', sa.String(length=100), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('system_requirements', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=True),
    sa.Column('players', sa.Integer(), nullable=False),
    sa.Column('related_games', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=180), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('game')
    # ### end Alembic commands ###
